
footer:
- {icon: 'github', link: 'https://github.com/hubba368'}
- {icon: 'twitter', link: 'https://twitter.com/eleeoht1'}
- {icon: 'itch-io', link: 'https://hubba368.itch.io/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/elliott-bowman-6b605859/'}

